### PR TITLE
Cloudflare changes

### PR DESCRIPTION
**Pull request by rnbguy**
I found your project from crates.io. Cloudflare changed a lot over the last 10 months. So I modified the code to reflect those changes. But it is still not working. Will you be willing to look into it? My changes are complementary to your codebase. So it is basically the same as before.

### CODE REVIEW

**Comment by acgxv** [comment]
Thank you, but I'm a little busy these day. Could you update the parse-thing from https://github.com/Anorov/cloudflare-scrape?

**Comment by rnbguy** [comment]
No problem. My modifications are based on my observations on Chrome DevTools. I didn't go through cloudflare-scrape's code before. On a quick glance, the parsing part seems fine. Maybe I missed some headers. I will look into it. Thanks.

**Comment by rnbguy** [comment]
I have fixed it. You can publish the current commit to crates.io after testing it.

Now that it is working, is it okay if I refactor the codebase?

**Comment by acgxv** [comment]
Looks good to me. Thank you.

I'll publish to crates.io little later.

**Pull request merged**
